### ISSUE TITLE
tuxedofancontrol shows wrong GPU temperature

### ISSUE THREAD

**Issue by agrizzli** [tuxedocomputers/tuxedo-fan-control#15]
When running in NVIDIA mode (nvidia-smi installed), then tuxedofancontrol GUI will show wrong GPU tempreture, which might be utilization instead. Please refer to screenshot attached.
![screenshot from 2019-03-06 12-34-23](https://user-images.githubusercontent.com/45446581/53878453-338a5600-400c-11e9-81d8-edffa99b4754.png)

**Comment by tuxedochris** [comment]
Hi agrizzli,

i need more informations for this issue
- what version is in use?
- what device is in used?
- how install way was used
- please send logs (logs can find under /var/log/tuxedo-fan/)

Cheers
Chris

**Comment by agrizzli** [comment]
Hi Chris,

I used current version from master branch. It is running on TUXEDO Book XP1508 with GeForce GTX 1070. I installed it the way described on GitHub repo's README. Will send logs later.

Arthur

**Comment by agrizzli** [comment]
Here are log files, which were logged immediately after installation and activation of tuxedofancontrol service.

Unfortunately I cannot provide a video, but when you open tuxedofancontrol tool and NVIDIA settings at same time, and click to GPU Thermal Settings there, then shown GPU temperature in tuxedofancontrol tool switches to correct value for a half second and fall immediately to 1 again.

[tuxedo-fan.zip](https://github.com/tuxedocomputers/tuxedo-fan-control/files/2939767/tuxedo-fan.zip)

**Comment by alexanderdurr** [comment]
@tuxedochris @agrizzli 
I've the same issue with the same model.
`sudo tuxedofancontrol --show`
shows for the Nvidia card the correct temperature in remoteTemp and in localTemp the wrong temperature 1, which is also shown in the GUI.

**Comment by tuxedochris** [comment]
Hi,

the TUXEDO Fan control poll the EC for getting the temperature. The problem is, we get in undefinded intervals the temperature of 1 Grad Celsius. I have no idea why we get this value in the case and we solve this issue.

The question is, was the 1 Grad Celsius always show by you? 

Cheers
Chris

**Comment by agrizzli** [comment]
Hi Chris,

display of 1 grad was most of the time. It switched to correct temperature only sometimes for very short time (less then a second). Maybe coincidentally in this moment I clicked in NVIDIA settings.

**Comment by tuxedochris** [comment]
Hi agrizzli,

can you pull the current version and test it?

Cheers
Chris

**Comment by agrizzli** [comment]
Hey Chris,

I don’t own that tuxedo laptop anymore. Hence I have no possibility to test it reliably...

**Comment by perry123456** [comment]
Hi,

this issue is reproducible for me, too.
tuxedofancontrol version 0.1.7
Tuxedo product: TUXEDO Book XP1508
Sticker on laptop's bottom side says: Clevo Model P955EP

Please find the logs of tuxedofancontrol from my machine attached.
It looks like we have a simple UI updating problem here because in the daemon's log the GPU temperature is noted correctly.

CU
[tuxedo-fan-logs.zip](https://github.com/tuxedocomputers/tuxedo-fan-control/files/3389162/tuxedo-fan-logs.zip)

**Comment by tuxedoxt** [comment]
Hello,

as presumed, it was a problem in the GUI part. I have made a few updates including two small changes that should solve this issue.

Please have a try with version 0.1.8.

- Christoffer
