### ISSUE TITLE
Make daemon run without Xvfb

### ISSUE THREAD

**Issue by scitor** [tuxedocomputers/tuxedo-fan-control#21]
This is the first daemon I see that needs a frame buffer to run in the background?!

`ExecStart=/bin/bash -c "Xvfb :99 & export DISPLAY=:99 && %TFCPATH% --startdaemon"` 

You already have a native binary, how about reducing 95% resource requirements by removing all the bloaty web-technology stuff from a low-level hardware management daemon?

**Comment by tuxedoxt** [comment]
Correct, this is.. weird. The GUI software is an electron application and I guess that out of convenience the daemon also. Because of this the "graphical part" needs to be somewhere, hence Xvfb. Electron is practical for GUIs but of course makes no sense for a service. A change is in the works, but for now it is what it is.

**Comment by FSMaxB-dooshop** [comment]
Wouldn't it be possible to run the daemon part directly via node?

**Comment by tuxedoxt** [comment]
You are right. To be able to reuse the important things this seems like the best option and is in fact the current plan ;) The base is currently being rewritten for this and to fit additional purposes.

**Comment by scitor** [comment]
That's cool. Although I'd prefer code managing a hardware part in C or some other compiled language, this would at least remove the framebuffer requirement.

**Comment by quertrakt** [comment]
i am having an issue that might be related to this...

i am on fedora30 and whenever the tuxedofancontrol.service is running, all flatpak-installed apps that are based on electron, are not being rendered. they get all system-tray-icons and notifiactions and are obviously running, but they are not being put on the screen.
when i stop the tuxedofancontrol.servce, all those apps are being stopped too.
if i install those apps via the standard fedora repositories, everything works fine. and it only happens with apps that are built on electron. filezilla for example still works fine even when installed as flatpak.

can you confirm, that all that happens because of the use of Xvfb? if so, i will just wait for your rewrite of the code :)

if not, i'd open a new issue for this.

**Comment by tuxedoxt** [comment]
Hmm, I do not understand all steps that would lead to this behaviour. But if the exported (hidden) DISPLAY is being used by other applications they certainly would not be displayed on screen. I have not observed this behaviour on any machines I have tested it on and I am not sure what is different in your case. Is the *tuxedofancontrol* application GUI also hidden on start?

**Comment by quertrakt** [comment]
thanks for your answer!
yeah, i can see the application GUI. giving the sudo it needs is a bit ugly on wayland, but i can do it ;)
how can i check whether the other apps use the same exported DISPLAY? and after finding out: what can i do to alter this behaviour?
i'm interested in what's different on my side, but again: if it's gonna be okay after you are done rewriting the code, i'm fine with that.

**Comment by tuxedoxt** [comment]
If you start an app from a shell you can `echo $DISPLAY`, this should print :99 if it's active in the scope.

I'm rather certain it will be fixed in any case when Xvfb is removed. You could maybe try to re-export the original DISPLAY variable after the service is started. Or experiment with using `xvfb-run -a` to start the service, in the meantime. Not sure if it will be practical though.

**Comment by scitor** [comment]
Closing this as it became obsolete. Checkout [Fancontrol](https://git.estate/scitor/fancontrol/src/branch/master/fancontrol.cpp) if you're still interested in a solution.

**Comment by FSMaxB-dooshop** [comment]
@scitor Can you please elaborate on how it became obsolete?

**Comment by FSMaxB-dooshop** [comment]
You mean your `autofan.sh` script?

**Comment by scitor** [comment]
Yes, the linked project uses the binary as simple command line tool, where one can set the values directly. The `autofan.sh` uses this to 'simulate' my own idea of fan automation. (Could turn out bad, but so far it works quite well, even under heavy load on `performance` power profile)

It's not a ready made tool for people to use, like the Electron App, so it's not a complete solution. It's more a starting point for everybody not wanting the complexity of the original.

Technically the issue isn't actually solved in this project, so closing it was probably the wrong thing.

**Comment by maulwuff** [comment]
@scitor can you help me with this one?
```
./autofan.sh: Zeile 20: printf: 39.98: Ungültige Zahl.
setting fan=1 duty=0 Wrong fan duty to write: 0 < 0 < 256 target=40 temp=41
```

**Comment by scitor** [comment]
@maulwuff This seems like a locales problem since German doesn't recognize . (dot) as a decimal separator. Try setting `LC_NUMERIC="en_US.UTF-8"` at the top of the script. I will add it to the script soon, thanks for reporting.

**Comment by tuxedoxt** [comment]
As TCC (TUXEDO Control Center) is officially released and replacing TFC I will close this issue. As mentioned previously TFC will not get this fix, but TCC for sure does not use Xvfb ;)

**Comment by maulwuff** [comment]
Where can we find TCC?

**Comment by vinzv** [comment]
> Where can we find TCC?

Already in our package repositories and soon here on GitHub. We'll of course announce it via social media as well.
